//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppListaDeCompras
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY
    {
        public int ID_HISTORY { get; set; }
        public Nullable<int> ID_USERS { get; set; }
        public Nullable<int> ID_PRODUCT { get; set; }
        public int AMOUNT { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual USER USER { get; set; }
    }
}
